# Spring Boot configuration
spring:
  #security with oauth
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23lilXtztzgHWuyj6Y
            clientSecret: be259efaedbd819f60d15396d946624499d070c1
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://manny.db.elephantsql.com/lvvpggxj
    username: lvvpggxj
    password: C1hiIMrOGIClreH2XoN7ORHX3rFV97hY
  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Server configuration
server:
  port: 8080
# Security configuration
security:
  user:
    name: user
password: user